const images = {
	'16th': 'https://imgur.com/WVQTIeg',
	'16thRest': 'https://imgur.com/pGK1zHi',
	'8th216ths': 'https://imgur.com/dV2FeTu',
	'16th8th16th': 'https://imgur.com/JyL1gXX',
	'216ths8th': 'https://imgur.com/bvCaUHM',
	'416ths': 'https://imgur.com/G6V1pLG',
	'44TimeSig': 'https://imgur.com/6Pd8cuZ',
	'8th': 'https://imgur.com/IHOVoOR',
	'8thInContext': 'https://imgur.com/ZgyfVNE',
	'8thRest': 'https://imgur.com/dciCt8l',
	'8thTriplet': 'https://imgur.com/ZAFztlj',
	'barLine': 'https://imgur.com/gr7ul3S',
	'beamed8ths': 'https://imgur.com/6UrO8hn',
	'dotted8th': 'https://imgur.com/wkIWlVi',
	'dotted8th16th': 'https://imgur.com/d7ohrom',
	'dottedHalf': 'https://imgur.com/XTnDgjY',
	'dottedHalfInContext': 'https://imgur.com/dBBMLjr',
	'dottedQuarter': 'https://imgur.com/wKlzbpS',
	'dottedQuarterInContext': 'https://imgur.com/geuTNXy',
	'doubleBarLine': 'https://imgur.com/yUMSFfA',
	'half': 'https://imgur.com/ts9pR4H',
	'halfInContext': 'https://imgur.com/Kmgo776',
	'halfRest': 'https://imgur.com/PRDm4Mr',
	'quarter': 'https://imgur.com/AOCeRrj',
	'quarterInContext': 'https://imgur.com/0Cdg1cf',
	'quarterRest': 'https://imgur.com/6SEvM2i',
	'quarterTriplet': 'https://imgur.com/49DvKrI',
	'16thDotted8th': 'https://imgur.com/3d2iJeG',
	'whole': 'https://imgur.com/eoiRnOg',
	'wholeInContext': 'https://imgur.com/QI7Gc6o',
	'wholeRest': 'https://imgur.com/CR3BCbn',
	'wholeRestInContext': 'https://imgur.com/kpPxZVU'
}

export default images;